version: '3'
services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=water_sensor
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080